export const areaContent = [
    {
        title: '1ккв',
        photos: [
            {photo: '/home/layout/slides/1kkv_slide1.webp'},
            {photo: '/home/layout/slides/1kkv_slide2.webp'},
            {photo: '/home/layout/slides/1kkv_slide3.webp'},
            {photo: '/home/layout/slides/1kkv_slide4.webp'},
            {photo: '/home/layout/slides/1kkv_slide5.webp'},
            {photo: '/home/layout/slides/1kkv_slide6.webp'},
            {photo: '/home/layout/slides/1kkv_slide7.webp'},
            {photo: '/home/layout/slides/1kkv_slide8.webp'},
            {photo: '/home/layout/slides/1kkv_slide9.webp'},
        ],
        areas: [
            {area: 31.87, photo: '/home/layout/31.87_area.webp'},
            {area: 32.67, photo: '/home/layout/32.67_area.webp'},
            {area: 32.38, photo: '/home/layout/32.38_area.webp'},
            {area: 32.81, photo: '/home/layout/32.81_area.webp'},
            {area: 35.37, photo: '/home/layout/35.37_area.webp'},
            {area: 35.38, photo: '/home/layout/35.38_area.webp'},
            {area: 35.41, photo: '/home/layout/35.41_area.webp'},
            {area: 35.80, photo: '/home/layout/35.80_area.webp'},
            {area: 35.81, photo: '/home/layout/35.81_area.webp'},
            {area: 35.99, photo: '/home/layout/35.99_area.webp'},
            {area: 36.00, photo: '/home/layout/36.00_area.webp'},
            {area: 36.24, photo: '/home/layout/36.24_area.webp'},
            {area: 36.27, photo: '/home/layout/36.27_area.webp'},
            {area: 38.19, photo: '/home/layout/38.19_area.webp'},
            {area: 38.56, photo: '/home/layout/38.56_area.webp'},
        ],
    },
    {
        title: '2ккв',
        photos: [
            {photo: '/home/layout/slides/2kkv_slide1.webp'},
            {photo: '/home/layout/slides/2kkv_slide2.webp'},
            {photo: '/home/layout/slides/2kkv_slide3.webp'},
            {photo: '/home/layout/slides/2kkv_slide4.webp'},
            {photo: '/home/layout/slides/2kkv_slide5.webp'},
            {photo: '/home/layout/slides/2kkv_slide6.webp'},
            {photo: '/home/layout/slides/2kkv_slide7.webp'},
            {photo: '/home/layout/slides/2kkv_slide8.webp'},
            {photo: '/home/layout/slides/2kkv_slide9.webp'},
            {photo: '/home/layout/slides/2kkv_slide10.webp'},
            {photo: '/home/layout/slides/2kkv_slide11.webp'},
            {photo: '/home/layout/slides/2kkv_slide12.webp'},
            {photo: '/home/layout/slides/2kkv_slide13.webp'},
            {photo: '/home/layout/slides/2kkv_slide14.webp'},
            {photo: '/home/layout/slides/2kkv_slide15.webp'},
            {photo: '/home/layout/slides/2kkv_slide16.webp'},
        ],
        areas: [
            {area: 45.26, photo: '/home/layout/45.26_area.webp'},
            {area: 48.30, photo: '/home/layout/48.30_area.webp'},
            {area: 48.31, photo: '/home/layout/48.31_area.webp'},
            {area: 48.73, photo: '/home/layout/48.73_area.webp'},
            {area: 53.43, photo: '/home/layout/53.43_area.webp'},
            {area: 55.23, photo: '/home/layout/55.23_area.webp'},
            {area: 55.78, photo: '/home/layout/55.78_area.webp'},
            {area: 62.44, photo: '/home/layout/62.44_area.webp'},
            {area: 62.45, photo: '/home/layout/62.45_area.webp'},
            {area: 64.56, photo: '/home/layout/64.56_area.webp'},
            {area: 66.52, photo: '/home/layout/66.52_area.webp'},
        ],
    },
    {
        title: '3ккв',
        photos: [
            {photo: '/home/layout/slides/3kkv_slide1.webp'},
            {photo: '/home/layout/slides/3kkv_slide2.webp'},
            {photo: '/home/layout/slides/3kkv_slide3.webp'},
            {photo: '/home/layout/slides/3kkv_slide4.webp'},
            {photo: '/home/layout/slides/3kkv_slide5.webp'},
            {photo: '/home/layout/slides/3kkv_slide6.webp'},
            {photo: '/home/layout/slides/3kkv_slide7.webp'},
            {photo: '/home/layout/slides/3kkv_slide8.webp'},
            {photo: '/home/layout/slides/3kkv_slide9.webp'},
            {photo: '/home/layout/slides/3kkv_slide10.webp'},
        ],
        areas: [
            {area: 86.55, photo: '/home/layout/86.55_area.webp'},
        ],
    },
]